services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    # environment:
    #   - NODE_ENV=production
    #   - AUTH_SECRET=${AUTH_SECRET}
    #   - AUTH_TRUST_HOST=${AUTH_TRUST_HOST}
    #   - BACKEND_BASE_URL=${BACKEND_BASE_URL}
    #   - BACKEND_SCHEMA_URL=${BACKEND_SCHEMA_URL}
    #   - BACKEND_SYSTEM_TOKEN=${BACKEND_SYSTEM_TOKEN}
    #   - FRONTEND_BASE_URL=${FRONTEND_BASE_URL}
    #   - NEXT_PUBLIC_UPLOAD_FILES_HOST=${NEXT_PUBLIC_UPLOAD_FILES_HOST}
    # env_file:
    #   - .env
    restart: unless-stopped
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # Optional: Add a development service that mounts the source code
  nextjs-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    # environment:
    #   - NODE_ENV=development
    #   - AUTH_SECRET=${AUTH_SECRET}
    #   - AUTH_TRUST_HOST=${AUTH_TRUST_HOST}
    #   - BACKEND_BASE_URL=${BACKEND_BASE_URL}
    #   - BACKEND_SCHEMA_URL=${BACKEND_SCHEMA_URL}
    #   - BACKEND_SYSTEM_TOKEN=${BACKEND_SYSTEM_TOKEN}
    #   - FRONTEND_BASE_URL=${FRONTEND_BASE_URL}
    #   - NEXT_PUBLIC_UPLOAD_FILES_HOST=${NEXT_PUBLIC_UPLOAD_FILES_HOST}
    # env_file:
    #   - .env
    command: pnpm run dev
    profiles:
      - dev
    networks:
      - app-network

networks:
  app-network:
    driver: bridge